apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: us-east-1
  version: "1.34"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

iam:
  serviceRoleARN: arn:aws:iam::851725639640:role/LabRole

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.small
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::851725639640:role/LabRole

addons:
  - name: aws-ebs-csi-driver
    version: latest
    serviceAccountRoleARN: arn:aws:iam::851725639640:role/LabRole