apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: final-cluster
  region: us-east-1

iam:
  withOIDC: true

nodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2