apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: final
data:
  HEADER_NAME: "Samir,Liliana,Yasmin"
  BUCKET_NAME: "clo835-group7-final-project"
  BG_IMAGE_S3_KEY: "image.png"
  BG_IMAGE_LOCAL_PATH: "./static/image.png"
