apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: final
data:
  HEADER_NAME: "Samir,Liliana,Yasmin"
  BUCKET_NAME: "finalproject-bucket-samir"
  BG_IMAGE_LOCAL_PATH: "./static/image.png"
