apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask
        image: 851725639640.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp
        ports:
          - containerPort: 81
        env:
        - name: HEADER_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: HEADER_NAME
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: BUCKET_NAME
        - name: BG_IMAGE_LOCAL_PATH
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: BG_IMAGE_LOCAL_PATH
        - name: BG_IMAGE_S3_KEY
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: BG_IMAGE_S3_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SESSION_TOKEN
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBPWD
        - name: DBHOST
          value: "mysql"
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: "employees"
